[package]
name = "refine"
version = "0.1.0"
edition = "2021"

[dependencies]
arboard = { version="3.2.0", default-features=false }

[profile.release]
strip = true  # Automatically strip symbols from the binary.
